name: Robot Framework

on:
  push:
    branches: [main]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
    
